apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-prometheus-stack.operator.fullname" . }}
  labels:
    app: {{ template "kube-prometheus-stack.operator.name" . }}
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-prometheus-stack.operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-prometheus-stack.operator.serviceAccountName" . }}
    namespace: {{ template "kube-prometheus-stack.namespace" . }}
