apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus-stack.operator.fullname" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.operator.name" . }}
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  endpoints:
    - port: https
      scheme: https
      honorLabels: true
      tlsConfig:
        serverName: {{ template "kube-prometheus-stack.operator.fullname" . }}
        ca:
          secret:
            name: {{ template "kube-prometheus-stack.fullname" . }}-admission
            key: ca
            optional: false
  selector:
    matchLabels:
      app: {{ template "kube-prometheus-stack.operator.name" . }}
      release: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "kube-prometheus-stack.namespace" .) | quote }}
