apiVersion: v2
name: cronjob
description: A chart for CronJobs.
icon: https://contino.github.io/intro-k8/images/kubernetes/cronjob.png
version: 1.0.0
appVersion: 1.0.0
type: application
keywords:
  - cronjob
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidshare.github.io/helm-charts
    tags:
      - fluidshare-common
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    version: "10.3.13"
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: "12.7.3"
    condition: redis.enabled
