{{- if eq .Values.loadtest.configmaps.lib "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "locust.fullname" . }}-lib
  labels:
    {{- include "locust.labels" . | nindent 4 }}
data:
  {{- ($.Files.Glob (printf "locustfiles/%s/lib/*" .Values.loadtest.name)).AsConfig | nindent 2 }}
{{- end }}
