{{- if eq .Values.loadtest.configmaps.locustfile "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}-locustfile
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- ($.Files.Glob (printf "locustfiles/%s/main.py" .Values.loadtest.name)).AsConfig | nindent 2 }}
{{- end }}
