apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "locust.fullname" . }}
  labels:
    {{- include "locust.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "locust.fullname" . }}
              servicePort: 8089
