apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "locust.fullname" . }}-master
  labels:
    component: master
    {{- include "locust.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: master
      {{- include "locust.selectorLabels" . | nindent 6 }}
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config-locust-lib: {{ include (print $.Template.BasePath "/configmap-locust-lib.yaml") . | sha256sum }}
        checksum/config-locust-locustfile: {{ include (print $.Template.BasePath "/configmap-locust-locustfile.yaml") . | sha256sum }}
        checksum/config-config: {{ include (print $.Template.BasePath "/configmap-config.yaml") . | sha256sum }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        component: master
        {{- include "locust.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "locust.fullname" . }}-master
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
          - sh
          - /config/docker-entrypoint.sh
        args:
          - --master
          - --locustfile=/mnt/locust/main.py
          - --host={{ .Values.loadtest.locust_host }}
          - --loglevel={{ .Values.master.logLevel }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.master.resources | nindent 10 }}
        volumeMounts:
          - name: locustfile
            mountPath: /mnt/locust
          - name: lib
            mountPath: /mnt/locust/lib
          - name: config
            mountPath: /config
        env:
          - name: LOCUST_HOST
            value: "{{ .Values.loadtest.locust_host }}"
        ports:
          - containerPort: 8089
            name: loc-master-web
            protocol: TCP
          - containerPort: 5557
            name: loc-master-p1
            protocol: TCP
          - containerPort: 5558
            name: loc-master-p2
            protocol: TCP
        livenessProbe:
          periodSeconds: 30
          initialDelaySeconds: 10
          timeoutSeconds: 30
          failureThreshold: 2
          httpGet:
            path: /
            port: 8089
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 2
          httpGet:
            path: /
            port: 8089
      restartPolicy: Always
      volumes:
        - name: lib
          configMap:
            name: {{ template "locust.configmap_lib" . }}
        - name: locustfile
          configMap:
            name: {{ template "locust.configmap_locustfile" . }}
        - name: config
          configMap:
            name: {{ template "locust.fullname" . }}-config
