apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-grafana-datasource
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-grafana
    grafana_datasource: "1"
    {{- include "kube-prometheus-stack.labels" $ | indent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://{{ template "kube-prometheus-stack.prometheus.fullname" . }}:9090/
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
