apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-etcd
  namespace: kube-system
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-kube-etcd
    jobLabel: kube-etcd
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    component: etcd
