{{- if .Values.swagger.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: swagger
spec:
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 60
    healthyThreshold: 1
    unhealthyThreshold: 10
    type: HTTP
    requestPath: /swagger.json
{{- end }}
