{{- if and .Values.ingress.tls .Values.ingress.forceHttps }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: FrontendConfig
metadata:
  name: force-https
spec:
  redirectToHttps:
    enabled: true
{{- end }}
