{{- if and .Values.grpc.enabled .Values.grpc.ingress.enabled .Values.ingress.enabled  }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-grpc
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    {{- end }}
    {{- if .Values.grpc.ingress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.grpc.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ tpl .Values.grpc.ingress.hostname . | quote }}
      http:
        paths:
          - path: /
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "grpc" "context" $)  | nindent 14 }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
      - {{ tpl .Values.ingress.hostname . | quote }}
      - {{ tpl .Values.grpc.ingress.hostname . | quote }}
      {{- range .Values.ingress.extraHosts }}
      - {{ .name }}
      {{- end }}
      secretName: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) | replace "." "-" }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.extraTls "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
