cronjobs:
  - name: hello
    schedule: "*/1 * * * *"
    image:
      registry: docker.io
      repository: busybox
      tag: latest
    command:
      - sh
      - -c
      - "date; echo Hello"
    successfulJobsHistoryLimit: 3
