envVars:
  FOO_BAR: test

cronjobs:
  - name: hello
    schedule: "*/1 * * * *"
    command:
      - date; echo Hello

postgresql:
  enabled: true
  wait: true
  postgresqlUsername: fluid
  postgresqlPassword: password
  postgresqlDatabase: golang
