apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
    {{- include "kube-prometheus-stack.labels" $ | indent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
      labels:
        app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
        {{- include "kube-prometheus-stack.labels" $ | indent 8 }}
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host={{ template "kube-prometheus-stack.operator.fullname" . }},{{ template "kube-prometheus-stack.operator.fullname" . }}.{{ template "kube-prometheus-stack.namespace" . }}.svc
            - --namespace={{ template "kube-prometheus-stack.namespace" . }}
            - --secret-name={{ template "kube-prometheus-stack.fullname" . }}-admission
      restartPolicy: OnFailure
      serviceAccountName: {{ template "kube-prometheus-stack.fullname" . }}-admission
      {{- with .Values.prometheusOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
