apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-patch
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-patch
    {{- include "kube-prometheus-stack.labels" $ | indent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-patch
      labels:
        app: {{ template "kube-prometheus-stack.name" $ }}-admission-patch
        {{- include "kube-prometheus-stack.labels" $ | indent 8 }}
    spec:
      containers:
        - name: patch
          image: jettech/kube-webhook-certgen:v1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name={{ template "kube-prometheus-stack.fullname" . }}-admission
            - --namespace={{ template "kube-prometheus-stack.namespace" . }}
            - --secret-name={{ template "kube-prometheus-stack.fullname" . }}-admission
            - --patch-failure-policy=Fail
      restartPolicy: OnFailure
      serviceAccountName: {{ template "kube-prometheus-stack.fullname" . }}-admission
      {{- if .Values.prometheusOperator.tolerations }}
      tolerations:
        {{- toYaml .Values.prometheusOperator.tolerations | indent 8 }}
      {{- end }}
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
