apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-dns
  namespace: kube-system
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-kube-dns
    jobLabel: kube-dns
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics-dnsmasq
      port: 10054
      protocol: TCP
      targetPort: 10054
    - name: http-metrics-skydns
      port: 10055
      protocol: TCP
      targetPort: 10055
  selector:
    k8s-app: kube-dns
