apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kube-prometheus-stack.alertmanager.fullname" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.alertmanager.name" . }}
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kube-prometheus-stack.alertmanager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-prometheus-stack.alertmanager.serviceAccountName" . }}
    namespace: {{ template "kube-prometheus-stack.namespace" . }}
