apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.alertmanager.fullname" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.alertmanager.name" . }}
    self-monitor: "true"
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: alertmanager
    alertmanager: {{ template "kube-prometheus-stack.alertmanager.fullname" . }}
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
