apiVersion: v2
name: locust
description: A Helm chart to launch Locust tests.
version: 1.0.0
appVersion: 1.4.1
icon: https://storage.googleapis.com/fluid-tidal-assets-stage/mclovin.jpg
type: application
keywords:
  - fluidtruck
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidshare.github.io/helm-charts
    tags:
      - fluidshare-common
    version: 1.x.x
