apiVersion: v2
name: nextjs
description: A chart for NextJS v10+.
icon: https://cdn.worldvectorlogo.com/logos/next-js.svg
version: 2.1.1
appVersion: 10.0.5
type: application
keywords:
  - nextjs
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidshare.github.io/helm-charts
    tags:
      - fluidshare-common
    version: 1.x.x
