apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-scheduler
  namespace: kube-system
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-kube-scheduler
    jobLabel: kube-scheduler
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    component: kube-scheduler
