apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-proxy
  namespace: kube-system
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-kube-proxy
    jobLabel: kube-proxy
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
