apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    component: master
    loadtest: {{ .Values.loadtest.name | quote }}
