apiVersion: v2
name: golang
description: A chart for Golang.
icon: https://golang.org/lib/godoc/images/go-logo-blue.svg
version: 1.0.0
appVersion: 4.1.17
type: application
keywords:
  - go
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidshare.github.io/helm-charts
    tags:
      - fluidshare-common
    version: 1.x.x
