apiVersion: v2
name: golang
description: A chart for Golang.
icon: https://golang.org/lib/godoc/images/go-logo-blue.svg
version: 3.2.0
appVersion: 4.1.17
type: application
keywords:
  - go
maintainers:
  - name: ellisio
    email: aellis@fluidtruck.com
dependencies:
  - name: common
    repository: https://fluidshare.github.io/helm-charts
    tags:
      - fluidshare-common
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    version: "10.4.9"
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: "14.4.0"
    condition: redis.enabled
