apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-coredns
  namespace: kube-system
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-coredns
    jobLabel: coredns
    {{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
